# Breast cancer prediction using Machine learning techniques 

In [1]:
#import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

In [2]:
#load the dataset
from sklearn.datasets import load_breast_cancer
df=load_breast_cancer()

In [61]:
df.feature_names


array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [69]:
df.target_names


'malignant'

In [50]:
df.DESCR

'.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.  For inst

In [3]:
#dependent and independent feature
x=df.data
y=df.target

In [4]:
x

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [64]:
x[1]

array([2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
       8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
       3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
       1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
       1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02])

In [65]:
y[1]

0

In [13]:
x.shape
y.shape

(569,)

In [11]:
# splitting dataset into train and test
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=44)

In [16]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

# Apply algorithms
here we will apply 7 algorithms and choose best one among all

In [41]:
# #Using Logistic Regression Algorithm to the Training Set
# from sklearn.linear_model import LogisticRegression
# classifier1 = LogisticRegression(random_state = 18)
# classifier1.fit(xtrain, ytrain)

# #Using KNeighborsClassifier Method of neighbors class to use Nearest Neighbor algorithm
# from sklearn.neighbors import KNeighborsClassifier
# classifier2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
# classifier2.fit(xtrain, ytrain)

# #Using SVC method of svm class to use Support Vector Machine Algorithm
# from sklearn.svm import SVC
# classifier3 = SVC(kernel = 'linear', random_state = 19)
# classifier3.fit(xtrain, ytrain)

# #Using SVC method of svm class to use Kernel SVM Algorithm
# from sklearn.svm import SVC
# classifier4 = SVC(kernel = 'rbf', random_state = 20)
# classifier4.fit(xtrain, ytrain)

# #Using GaussianNB method of naïve_bayes class to use Naïve Bayes Algorithm
# from sklearn.naive_bayes import GaussianNB
# classifier5 = GaussianNB()
# classifier5.fit(xtrain, ytrain)

# #Using DecisionTreeClassifier of tree class to use Decision Tree Algorithm
# from sklearn.tree import DecisionTreeClassifier
# classifier6 = DecisionTreeClassifier(criterion = 'entropy', random_state = 21)
# classifier6.fit(xtrain, ytrain)

# #Using RandomForestClassifier method of ensemble class to use Random Forest Classification algorithm
# from sklearn.ensemble import RandomForestClassifier
# classifier7 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 5)
# classifier7.fit(xtrain, ytrain)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=5)

In [42]:
#y_pred1=classifier1.predict(xtest)
#y_pred2=classifier2.predict(xtest)
#y_pred3=classifier3.predict(xtest)
y_pred4=classifier4.predict(xtest)
#y_pred5=classifier5.predict(xtest)
#y_pred6=classifier6.predict(xtest)
#y_pred7=classifier7.predict(xtest)

In [52]:
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score
acc1=accuracy_score(ytest,y_pred1) 
acc1

acc2=accuracy_score(ytest,y_pred2)      
acc2

acc3=accuracy_score(ytest,y_pred3)         
acc3

acc4=accuracy_score(ytest,y_pred4)      
acc4

acc5=accuracy_score(ytest,y_pred5)        
acc5

acc6=accuracy_score(ytest,y_pred6)         
acc6

acc7=accuracy_score(ytest,y_pred7)              
acc7

0.986013986013986

In [48]:
cm=confusion_matrix(ytest,y_pred4)
cm

array([[47,  1],
       [ 1, 94]], dtype=int64)

In [55]:
r1=recall_score(ytest,y_pred1)
r2=recall_score(ytest,y_pred2)
r3=recall_score(ytest,y_pred3)
r4=recall_score(ytest,y_pred4)
r5=recall_score(ytest,y_pred5)
r6=recall_score(ytest,y_pred6)
r7=recall_score(ytest,y_pred7)

In [56]:
list1=['Logistic Reg','KNN','SVM(linear)','SVM(rbf)','Naive bayes','Decision tree','Random forest']
list2=[acc1,acc2,acc3,acc4,acc5,acc6,acc7]
list3=[r1,r2,r3,r4,r5,r6,r7]

In [45]:
list2

[0.9790209790209791,
 0.951048951048951,
 0.972027972027972,
 0.986013986013986,
 0.951048951048951,
 0.958041958041958,
 0.965034965034965]

In [57]:
list3

[0.9789473684210527,
 0.9789473684210527,
 0.9789473684210527,
 0.9894736842105263,
 0.968421052631579,
 0.9578947368421052,
 0.9578947368421052]

In [58]:
# create a dataframe to compare all the results
df1=pd.DataFrame({"Model":list1,"Accuracy":list2,"recall score":list3})
df1

Model  Accuracy  recall score
0   Logistic Reg  0.979021      0.978947
1            KNN  0.951049      0.978947
2    SVM(linear)  0.972028      0.978947
3       SVM(rbf)  0.986014      0.989474
4    Naive bayes  0.951049      0.968421
5  Decision tree  0.958042      0.957895
6  Random forest  0.965035      0.957895

# conclusion: SVM with rbf kernel is best algorithm for given problem

In [60]:
# store this model in pickle file  
import pickle
pickle.dump(classifier4, open('cancer_model.pkl', 'wb'))

cancer_model = pickle.load(open('cancer_model.pkl', 'rb'))
print(cancer_model)

SVC(random_state=20)
